# Generated by Django 4.1.4 on 2022-12-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('maker', models.CharField(blank=True, max_length=1, null=True)),
                ('model', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('model', models.OneToOneField(db_column='model', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myApp.product')),
                ('speed', models.FloatField(blank=True, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('hd', models.IntegerField(blank=True, null=True)),
                ('screen', models.FloatField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laptop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('model', models.OneToOneField(db_column='model', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myApp.product')),
                ('speed', models.FloatField(blank=True, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('hd', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=5, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'printer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('model', models.OneToOneField(db_column='model', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myApp.product')),
                ('color', models.CharField(blank=True, max_length=5, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'printer',
                'managed': False,
            },
        ),
    ]
